# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hyperparameters_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_HyperparametersDialog(object):
    def setupUi(self, HyperparametersDialog):
        HyperparametersDialog.setObjectName("HyperparametersDialog")
        HyperparametersDialog.resize(329, 300)
        HyperparametersDialog.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(HyperparametersDialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.formLayout = QtWidgets.QFormLayout()
        self.formLayout.setObjectName("formLayout")
        self.mutationRateLabel = QtWidgets.QLabel(HyperparametersDialog)
        self.mutationRateLabel.setObjectName("mutationRateLabel")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.mutationRateLabel)
        self.mutationRateDoubleSpinBox = QtWidgets.QDoubleSpinBox(HyperparametersDialog)
        self.mutationRateDoubleSpinBox.setMaximum(1.0)
        self.mutationRateDoubleSpinBox.setSingleStep(0.01)
        self.mutationRateDoubleSpinBox.setObjectName("mutationRateDoubleSpinBox")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.mutationRateDoubleSpinBox)
        self.crossoverRateLabel = QtWidgets.QLabel(HyperparametersDialog)
        self.crossoverRateLabel.setObjectName("crossoverRateLabel")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.crossoverRateLabel)
        self.crossoverRateDoubleSpinBox = QtWidgets.QDoubleSpinBox(HyperparametersDialog)
        self.crossoverRateDoubleSpinBox.setMaximum(1.0)
        self.crossoverRateDoubleSpinBox.setSingleStep(0.01)
        self.crossoverRateDoubleSpinBox.setObjectName("crossoverRateDoubleSpinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.crossoverRateDoubleSpinBox)
        self.populationSizeLabel = QtWidgets.QLabel(HyperparametersDialog)
        self.populationSizeLabel.setObjectName("populationSizeLabel")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.populationSizeLabel)
        self.populationSizeSpinBox = QtWidgets.QSpinBox(HyperparametersDialog)
        self.populationSizeSpinBox.setMinimum(1)
        self.populationSizeSpinBox.setMaximum(1000)
        self.populationSizeSpinBox.setObjectName("populationSizeSpinBox")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.populationSizeSpinBox)
        self.maxGenerationsAmountLabel = QtWidgets.QLabel(HyperparametersDialog)
        self.maxGenerationsAmountLabel.setObjectName("maxGenerationsAmountLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.maxGenerationsAmountLabel)
        self.maxGenerationsAmountSpinBox = QtWidgets.QSpinBox(HyperparametersDialog)
        self.maxGenerationsAmountSpinBox.setMinimum(2)
        self.maxGenerationsAmountSpinBox.setMaximum(100000)
        self.maxGenerationsAmountSpinBox.setObjectName("maxGenerationsAmountSpinBox")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.maxGenerationsAmountSpinBox)
        self.selectionLabel = QtWidgets.QLabel(HyperparametersDialog)
        self.selectionLabel.setObjectName("selectionLabel")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.selectionLabel)
        self.selectionComboBox = QtWidgets.QComboBox(HyperparametersDialog)
        self.selectionComboBox.setObjectName("selectionComboBox")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.selectionComboBox)
        self.crossoverLabel = QtWidgets.QLabel(HyperparametersDialog)
        self.crossoverLabel.setObjectName("crossoverLabel")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.crossoverLabel)
        self.crossoverComboBox = QtWidgets.QComboBox(HyperparametersDialog)
        self.crossoverComboBox.setObjectName("crossoverComboBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.crossoverComboBox)
        self.mutationLabel = QtWidgets.QLabel(HyperparametersDialog)
        self.mutationLabel.setObjectName("mutationLabel")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.mutationLabel)
        self.mutationComboBox = QtWidgets.QComboBox(HyperparametersDialog)
        self.mutationComboBox.setObjectName("mutationComboBox")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.mutationComboBox)
        self.verticalLayout.addLayout(self.formLayout)
        self.buttonBox = QtWidgets.QDialogButtonBox(HyperparametersDialog)
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout.addWidget(self.buttonBox)

        self.retranslateUi(HyperparametersDialog)
        self.buttonBox.accepted.connect(HyperparametersDialog.accept) # type: ignore
        self.buttonBox.rejected.connect(HyperparametersDialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(HyperparametersDialog)

    def retranslateUi(self, HyperparametersDialog):
        _translate = QtCore.QCoreApplication.translate
        HyperparametersDialog.setWindowTitle(_translate("HyperparametersDialog", "Hyperparameters"))
        self.mutationRateLabel.setText(_translate("HyperparametersDialog", "Mutation rate"))
        self.crossoverRateLabel.setText(_translate("HyperparametersDialog", "Crossover rate"))
        self.populationSizeLabel.setText(_translate("HyperparametersDialog", "Population size"))
        self.maxGenerationsAmountLabel.setText(_translate("HyperparametersDialog", "Max generations amount"))
        self.selectionLabel.setText(_translate("HyperparametersDialog", "Selection"))
        self.crossoverLabel.setText(_translate("HyperparametersDialog", "Crossover"))
        self.mutationLabel.setText(_translate("HyperparametersDialog", "Mutation"))
